/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
  // Deletes ALL existing entries
  await knex("contacts").del();

  // Inserts seed entries
  await knex("contacts").insert([
    {
      user_id: 1,
      name: "Alice Johnson",
      email: "alice@example.com",
      phone: "123-456-7890",
      company: "Acme Corp",
      job_title: "Sales Manager",
      notes: "Interested in VoIP features.",
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      user_id: 1,
      name: "Bob Smith",
      email: "bob@smithbiz.com",
      phone: "234-567-8901",
      company: "SmithBiz",
      job_title: "CTO",
      notes: "Asked about SMS integration.",
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      user_id: 1,
      name: "Carol Davis",
      email: "carol.davis@company.com",
      phone: "345-678-9012",
      company: "Company Inc.",
      job_title: "HR Lead",
      notes: "Wants a demo of internal calling features.",
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      user_id: 1,
      name: "David Lee",
      email: "davidl@leedev.com",
      phone: "456-789-0123",
      company: "Lee Dev Co.",
      job_title: "Software Engineer",
      notes: "Testing call logs export.",
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      user_id: 1,
      name: "Eva Green",
      email: "eva@greenagency.com",
      phone: "567-890-1234",
      company: "Green Agency",
      job_title: "Marketing Director",
      notes: "Discussed outbound call tracking.",
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      user_id: 1,
      name: "Frank White",
      email: "frank.white@whitehouse.com",
      phone: "678-901-2345",
      company: "White House Holdings",
      job_title: "CEO",
      notes: "Needs high reliability voice solution.",
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      user_id: 1,
      name: "Grace Kim",
      email: "grace@kimgroup.com",
      phone: "789-012-3456",
      company: "Kim Group",
      job_title: "COO",
      notes: "Requested call analytics.",
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      user_id: 1,
      name: "Henry Zhao",
      email: "henry.zhao@zhaotech.com",
      phone: "890-123-4567",
      company: "ZhaoTech",
      job_title: "Lead Developer",
      notes: "Exploring WebRTC integrations.",
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      user_id: 1,
      name: "Isabel Martinez",
      email: "isabel.martinez@example.org",
      phone: "901-234-5678",
      company: "Martinez Partners",
      job_title: "Consultant",
      notes: "Interested in multi-region support.",
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      user_id: 1,
      name: "Jack Lin",
      email: "jack.lin@teleco.com",
      phone: "112-233-3444",
      company: "TeleCo",
      job_title: "Product Manager",
      notes: "Requested product roadmap.",
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      user_id: 1,
      name: "Karen Xu",
      email: "karen.xu@xuventures.com",
      phone: "223-344-4555",
      company: "Xu Ventures",
      job_title: "Investor",
      notes: "Looking to invest in telephony tech.",
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      user_id: 1,
      name: "Leo Park",
      email: "leo.park@parklabs.com",
      phone: "334-455-5666",
      company: "Park Labs",
      job_title: "Researcher",
      notes: "Interested in VoIP latency metrics.",
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      user_id: 1,
      name: "Maria Gonzalez",
      email: "maria.g@glzgroup.com",
      phone: "445-566-6777",
      company: "GLZ Group",
      job_title: "Executive Assistant",
      notes: "Handles scheduling for the exec team.",
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      user_id: 1,
      name: "Nathan Reed",
      email: "nreed@reedtech.io",
      phone: "556-677-7888",
      company: "ReedTech",
      job_title: "DevOps Engineer",
      notes: "Asked about call recording storage.",
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      user_id: 1,
      name: "Olivia Brown",
      email: "olivia@browncorp.com",
      phone: "667-788-8999",
      company: "BrownCorp",
      job_title: "Customer Support Lead",
      notes: "Needs integrated call center tools.",
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  ]);
};
